import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata = {
  title: "cooking academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className="font-[Number] bg-[#101011]">
        <Header/>
        {children}
        <Footer/>
        <ToastContainer
          position="bottom-left"
          autoClose={3000}
          hideProgressBar={false}
          theme="dark"
        />
      </body>
    </html>
  );
}
