import "./globals.css";
import { Footer } from "../components/Footer";
import Header from "../components/Header";

export const metadata = {
  title: "cooking academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body
        className="font-[Number]"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
